addr/urls.py
from django.conf.urls import url
from . import views





urlpatterns = [
    url(r'^$', views.friend_list, name='friend_list'),
    url(r'^friend/(?P<pk>\d+)/$', views.friend_detail, name='friend_detail'),
    url(r'^friend/(?P<pk>\d+)/edit/$', views.friend_edit, name='friend_edit'),
    url(r'^friend/new/$', views.friend_new, name='friend_new'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('addr.urls', namespace='addr')),
]

addr/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Friend(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    name = models.CharField(max_length=10)
    phon_number_1= models.CharField(max_length=20)
    phon_number_2= models.CharField(max_length=20, blank=True, null=True)
    e_mail = models.EmailField(blank=True, null=True)
    created_date = models.DateTimeField(default=timezone.now())
    approved_friend = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def approve(self):
        self.approved_friend = True
        self.save()

    class Meta:
        ordering = ('name',)

addr/forms.py
from django import forms

from .models import Friend

class FriendForm(forms.ModelForm):

    class Meta:
        model = Friend
        fields = ('name', 'phon_number_1', 'phon_number_2', 'e_mail',)

addr/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from .models import Friend
from .forms import FriendForm

# Create your views here.


def friend_list(request):
    friends = Friend.objects.filter(approved_friend=1)
    return render(request, 'addr/friend_list.html',{'friends': friends})


def friend_detail(request, pk):
    friend = get_object_or_404(Friend, pk=pk)
    return render(request, 'addr/friend_detail.html', {'friend': friend})


def friend_new(request):
    if request.method == "POST":
        form = FriendForm(request.POST)
        if form.is_valid():
            friend = form.save(commit=False)
            friend.author = User.objects.get(username='admin')
            # friend.author = request.user
            friend.save()
            return redirect('addr:friend_detail', pk=friend.pk)
    else:
        form = FriendForm()
    return render(request, 'addr/friend_edit.html', {'form': form})


def friend_edit(request, pk):
    friend = get_object_or_404(Friend, pk=pk)
    if request.method == "POST":
        form = FriendForm(request.POST, instance=friend)
        if form.is_valid():
            friend = form.save(commit=False)
            friend.author = User.objects.get(username='admin')
            # friend.author = request.user
            friend.save()
            return redirect('addr:friend_detail', pk=friend.pk)
    else:
        form = FriendForm(instance=friend)
    return render(request, 'addr/friend_edit.html', {'form': form})

addr/templates/addr/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Address</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/addr.css' %}">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
</head>
<body>

<div class="page-header">
    {% if user.is_authenticated %}
    <a href="{% url 'addr:friend_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
    {% endif %}
    <h1><a href="{% url 'addr:friend_list' %}">Django Girls Address</a></h1>
</div>

<div class="content container">
    <div class="row">
        <div class="col-md-8">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

addr/templates/addr/friend_detail.html
{% extends 'addr/base.html' %}


{% block content %}
<div class="friend">

    {% if friend.approved_friend %}
    <b> 공개된 주소록입니다</b><br>
    {% endif %}
</div>
{% if user.is_authenticated %}
<a class="btn btn-default" href="{% url 'addr:friend_edit' pk=friend.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
{% endif %}
<div>
    <br>
    <ul>
        <li> 이 름 : {{ friend.name }}</li>
        <li> 연락처1 : {{ friend.phon_number_1 }}</li>
        <li> 연락처2 : {{ friend.phon_number_2 }}</li>
        <li> e - mail: {{ friend.e_mail }}</li>
    </ul>
</div>


{% endblock %}

addr/templates/addr/friend_edit.html
{% extends 'addr/base.html' %}


{% block content %}
<h1>New Frined</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">등록</button>
    </form>

{% endblock %}

addr/templates/addr/friend_list.html
{% extends 'addr/base.html' %}


{% block content %}
            {% for friend in friends %}
            <div class="friend">

                <ul>
                    <a href="{% url 'addr:friend_detail' pk=friend.pk %}">
                        <li> 이름 : {{ friend.name }} 연락처 : {{ friend.phon_number_1 }}</li>
                    </a>
                </ul>

            </div>

            {% endfor %}

{% endblock %}